### PR TITLE
Updated math plugin and fixed latex not displaying in spoiler tags

### PR DESCRIPTION
**Pull request by ehliang**
screen shot 2018-09-11 at 12 18 17 pm
screen shot 2018-09-11 at 12 19 08 pm

### CODE REVIEW

**Comment by kevincheng97** [comment]
What happens when you try to insert latex in a code block?

**Comment by ehliang** [comment]
image

It doesn't render in a code block but works in blockquote. Should it be made to work?

**Comment by kevincheng97** [comment]
No, that looks fine

**Comment by kevincheng97** [comment]
Is there a Ruby package manager? If so, can you maybe remove plugins and give install instructions so diffs aren't as big?

**Pull request merged**
